'use strict'
/**
 * @param {Egg.Application} app - egg application
 */
module.exports = app => {
  const { router, controller } = app
  router.get('/', controller.home.index)
  router.post('/api/getMsg', controller.msgs.getMsg)
  // pushMsg 短信
  router.post('/api/pushMsg', controller.pushMsg.create)
  router.delete('/api/pushMsg/:id', controller.pushMsg.destroy)
  router.put('/api/pushMsg/:id', controller.pushMsg.update)
  router.get('/api/pushMsg/:id', controller.pushMsg.show)
  router.get('/api/pushMsg', controller.pushMsg.index)
  router.delete('/api/pushMsg', controller.pushMsg.removes)
  router.resources('pushMsg', '/api/pushMsg', controller.pushMsg)
  // news 新闻
  router.post('/api/news', controller.news.create)
  router.delete('/api/news/:id', controller.news.destroy)
  router.put('/api/news/:id', controller.news.update)
  router.get('/api/news/:id', controller.news.show)
  router.get('/api/news', controller.news.index)
  router.delete('/api/news', controller.news.removes)
  router.resources('news', '/api/news', controller.news)
  // task 任务
  router.post('/api/task', controller.task.create)
  router.delete('/api/task/:id', controller.task.destroy)
  router.put('/api/task/:id', controller.task.update)
  router.get('/api/task/:id', controller.task.show)
  router.get('/api/task', controller.task.index)
  router.get('/api/taskbyday', controller.task.indexbyday)
  router.delete('/api/task', controller.task.removes)
  router.resources('task', '/api/task', controller.task)
  // recipe 食谱
  router.post('/api/recipe', controller.recipe.create)
  router.delete('/api/recipe/:id', controller.recipe.destroy)
  router.put('/api/recipe/:id', controller.recipe.update)
  router.get('/api/recipe/:id', controller.recipe.show)
  router.get('/api/recipe', controller.recipe.index)
  router.get('/api/recipebyday', controller.recipe.indexbyday)
  router.delete('/api/recipe', controller.recipe.removes)
  router.resources('recipe', '/api/recipe', controller.recipe)
  // video 食谱
  router.post('/api/video', controller.video.create)
  router.delete('/api/video/:id', controller.video.destroy)
  router.put('/api/video/:id', controller.video.update)
  router.get('/api/video/:id', controller.video.show)
  router.get('/api/video', controller.video.index)
  router.delete('/api/video', controller.video.removes)
  router.resources('video', '/api/video', controller.video)
  // appData app信息
  router.post('/api/appData', controller.appData.create)
  router.delete('/api/appData/:id', controller.appData.destroy)
  router.put('/api/appData/:id', controller.appData.update)
  router.get('/api/appData/:id', controller.appData.show)
  router.get('/api/appData', controller.appData.index)
  router.delete('/api/appData', controller.appData.removes)
  router.resources('appData', '/api/appData', controller.appData)
  // baseData 基础数据
  router.post('/api/baseData', controller.baseData.create)
  router.delete('/api/baseData/:id', controller.baseData.destroy)
  router.put('/api/baseData/:id', controller.baseData.update)
  router.get('/api/baseData/:id', controller.baseData.show)
  router.get('/api/baseData', controller.baseData.index)
  router.delete('/api/baseData', controller.baseData.removes)
  router.resources('baseData', '/api/baseData', controller.baseData)
  // vipData 会员数据
  router.post('/api/vipData', controller.vipData.create)
  router.delete('/api/vipData/:id', controller.vipData.destroy)
  router.put('/api/vipData/:id', controller.vipData.update)
  router.get('/api/vipData/:id', controller.vipData.show)
  router.get('/api/vipData', controller.vipData.index)
  router.delete('/api/vipData', controller.vipData.removes)
  router.resources('vipData', '/api/vipData', controller.vipData)
  // branch 分俱乐部
  router.post('/api/branch', controller.branch.create)
  router.delete('/api/branch/:id', controller.branch.destroy)
  router.put('/api/branch/:id', controller.branch.update)
  router.get('/api/branch/:id', controller.branch.show)
  router.get('/api/branch', controller.branch.index)
  router.delete('/api/branch', controller.branch.removes)
  router.resources('branch', '/api/branch', controller.branch)
  // app 会员信息
  router.post('/api/appInfo', controller.appInfo.create)
  router.delete('/api/appInfo/:id', controller.appInfo.destroy)
  router.put('/api/appInfo/:id', controller.appInfo.update)
  router.get('/api/appInfo/:id', controller.appInfo.show)
  router.get('/api/appInfo', controller.appInfo.index)
  router.delete('/api/appInfo', controller.appInfo.removes)
  router.resources('appInfo', '/api/appInfo', controller.appInfo)
  // vip 会员信息
  router.post('/api/vip', controller.vip.create)
  router.delete('/api/vip/:id', controller.vip.destroy)
  router.put('/api/vip/:id', controller.vip.update)
  router.get('/api/vip/:id', controller.vip.show)
  router.get('/api/vip', controller.vip.index)
  router.delete('/api/vip', controller.vip.removes)
  router.resources('vip', '/api/vip', controller.vip)
  // club 俱乐部
  router.post('/api/club', controller.club.create)
  router.delete('/api/club/:id', controller.club.destroy)
  router.put('/api/club/:id', controller.club.update)
  router.get('/api/club/:id', controller.club.show)
  router.get('/api/club', controller.club.index)
  router.delete('/api/club', controller.club.removes)
  router.resources('club', '/api/club', controller.club)
  // role 角色
  router.post('/api/role', controller.role.create)
  router.delete('/api/role/:id', controller.role.destroy)
  router.put('/api/role/:id', controller.role.update)
  router.get('/api/role/:id', controller.role.show)
  router.get('/api/role', controller.role.index)
  router.delete('/api/role', controller.role.removes)
  router.resources('role', '/api/role', controller.role)
  // area 区域
  router.post('/api/area', controller.area.create)
  router.delete('/api/area/:id', controller.area.destroy)
  router.put('/api/area/:id', controller.area.update)
  router.get('/api/area/:id', controller.area.show)
  router.get('/api/area', controller.area.index)
  router.delete('/api/area', controller.area.removes)
  router.resources('area', '/api/area', controller.area)
  // userAccess 用户登录
  router.post('/api/user/access/login', controller.userAccess.login)
  router.post('/api/user/access/usernameLogin', controller.userAccess.usernameLogin)
  router.get('/api/user/access/current',  controller.userAccess.current)
  // router.get('/api/user/access/current', app.jwt, controller.userAccess.current)
  router.get('/api/user/access/logout', controller.userAccess.logout)
  // router.put('/api/user/access/resetPsw', app.jwt, controller.userAccess.resetPsw)
  router.put('/api/user/access/resetPsw',  controller.userAccess.resetPsw)
  // user 用户
  router.post('/api/user', controller.user.create)
  // router.post('/api/userAdmin', controller.user.createAdmin)
  router.delete('/api/user/:id', controller.user.destroy)
  router.put('/api/user/:id', controller.user.update)
  router.put('/api/user/resetPsd/:id', controller.user.resetPsd)
  router.get('/api/user/:id', controller.user.show)
  router.get('/api/importXls', controller.user.importXls)
  router.put('/api/userUpdate', controller.user.updateByMobile)
  router.get('/api/user', controller.user.index)
  router.get('/api/indexcoach', controller.user.indexCoach)
  router.get('/api/sortbyweight', controller.user.sortbyweight)
  router.get('/api/user1', controller.user.index1)
  router.get('/api/test', controller.user.test)
  // router.get('/api/user/admin/all', controller.user.allAdmin)
  router.delete('/api/user', controller.user.removes)
  router.resources('user', '/api/user', controller.user)
  // router.resources('user', '/api/userAdmin', controller.user)
  //所有普通管理员
  router.get('/api/admin', controller.user.allAdmin)
  // router.resources('user', '/api/admin', controller.user)
  //所有普通教练
  router.get('/api/coach', controller.user.allCoach)
  router.get('/api/student', controller.user.allUser)
  // router.resources('user', '/api/coach', controller.user)
  // upload 文件上传
  router.post('/api/upload', controller.upload.create)
  router.post('/api/upload/url', controller.upload.url)
  router.post('/api/uploads', controller.upload.multiple)
  router.delete('/api/upload/:id', controller.upload.destroy)
  router.put('/api/upload/:id', controller.upload.update)
  router.post('/api/upload/:id', controller.upload.update) // Ant Design Pro
  router.put('/api/upload/:id/extra', controller.upload.extra)
  router.get('/api/upload/:id', controller.upload.show)
  router.get('/api/upload', controller.upload.index)
  router.delete('/api/upload', controller.upload.removes)
  router.resources('upload', '/api/upload', controller.upload)
}